/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/ROOM.glb");
  return (
    <group {...props} dispose={null} position={[0,15,0]} castShadow={true}  >
      <mesh
        name="Plane001"
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={nodes.Plane001.material}
        position={[-23.48134613, -0.07398158, 0.12562239]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.17732143, -16.4496212, -23.71066475]}
        userData={{ name: "Plane.001" }}
      />
      <mesh
        name="Cube001"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube001.material}
        position={[-17.82465172, 2.00457597, 16.22778893]}
        scale={[4.78257751, 0.41458231, 6.68879795]}
        userData={{ name: "Cube.001" }}
      />
      <mesh
        name="Cube002"
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials["Material.008"]}
        position={[-17.82465172, 29.0352726, 15.09196186]}
        rotation={[0, 0, -Math.PI]}
        scale={[-5.97490025, -0.41458231, -6.45017529]}
        userData={{ name: "Cube.002" }}
      />
      <mesh
        name="Cube003"
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={nodes.Cube003.material}
        position={[-20.42005539, 2.58910203, 20.92716217]}
        rotation={[0, -0.48286103, 0]}
        scale={[1.62692821, 0.19971517, 0.68272609]}
        userData={{ name: "Cube.003" }}
      />
      <mesh
        name="Circle"
        castShadow
        receiveShadow
        geometry={nodes.Circle.geometry}
        material={materials["Material.010"]}
        position={[-0.54672432, 15.37719631, 0.03763387]}
        userData={{ name: "Circle" }}
      />
      <group
        name="Plane005"
        position={[-23.48134613, -0.07398158, 0.12562239]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.17732143, -16.4496212, -23.71066475]}
        userData={{ name: "Plane.005" }}
      >
        <mesh
          name="Plane005_1"
          castShadow
          receiveShadow
          geometry={nodes.Plane005_1.geometry}
          material={materials.Glass}
        />
        <mesh
          name="Plane005_2"
          castShadow
          receiveShadow
          geometry={nodes.Plane005_2.geometry}
          material={materials["Wood N/ Texture"]}
        />
        <mesh
          name="Plane005_3"
          castShadow
          receiveShadow
          geometry={nodes.Plane005_3.geometry}
          material={materials.Material}
        />
      </group>
      <group
        name="Plane004"
        position={[-23.48134613, -0.07398158, -19.14285469]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.17732143, -16.4496212, -23.71066475]}
        userData={{ name: "Plane.004" }}
      >
        <mesh
          name="Plane006_1"
          castShadow
          receiveShadow
          geometry={nodes.Plane006_1.geometry}
          material={materials.Glass}
        />
        <mesh
          name="Plane006_2"
          castShadow
          receiveShadow
          geometry={nodes.Plane006_2.geometry}
          material={materials["Wood N/ Texture"]}
        />
        <mesh
          name="Plane006_3"
          castShadow
          receiveShadow
          geometry={nodes.Plane006_3.geometry}
          material={materials.Material}
        />
      </group>
      <group
        name="Plane006"
        position={[-9.79831028, 0.87689829, 13.21822453]}
        rotation={[0, -1.50041387, -Math.PI]}
        scale={[-0.17732143, -16.4496212, -23.71066666]}
        userData={{ name: "Plane.006" }}
      >
        <mesh
          name="Plane007_1"
          castShadow
          receiveShadow
          geometry={nodes.Plane007_1.geometry}
          material={materials.Glass}
        />
        <mesh
          name="Plane007_2"
          castShadow
          receiveShadow
          geometry={nodes.Plane007_2.geometry}
          material={materials["Wood N/ Texture"]}
        />
        <mesh
          name="Plane007_3"
          castShadow
          receiveShadow
          geometry={nodes.Plane007_3.geometry}
          material={materials.Material}
        />
      </group>
      <mesh
        name="Cube004"
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={nodes.Cube004.material}
        position={[-15.57807541, 2.58910203, 20.92716217]}
        rotation={[-Math.PI, 0.03756055, -Math.PI]}
        scale={[1.62692821, 0.19971517, 0.68272609]}
        userData={{ name: "Cube.004" }}
      />
      <mesh
        name="Cube005"
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={nodes.Cube005.material}
        position={[-20.42005539, 2.58910203, 16.20767021]}
        rotation={[0, -0.48286103, 0]}
        scale={[1.62692821, 0.19971517, 0.68272609]}
        userData={{ name: "Cube.005" }}
      />
      <group
        name="Circle001"
        position={[-0.54672432, 15.6404171, 0.03763387]}
        userData={{ name: "Circle.001" }}
      >
        <mesh
          name="Circle002_1"
          castShadow
          receiveShadow
          geometry={nodes.Circle002_1.geometry}
          material={materials["Material.019"]}
        />
        <mesh
          name="Circle002_2"
          castShadow
          receiveShadow
          geometry={nodes.Circle002_2.geometry}
          material={materials["Material.028"]}
        />
      </group>
      <group
        name="Cube006"
        position={[-20.68071175, 0, -0.83851767]}
        scale={[2.56262469, 0.14559522, 4.52186871]}
        userData={{ name: "Cube.006" }}
      >
        <mesh
          name="Cube006_1"
          castShadow
          receiveShadow
          geometry={nodes.Cube006_1.geometry}
          material={materials["Material.013"]}
        />
        <mesh
          name="Cube006_2"
          castShadow
          receiveShadow
          geometry={nodes.Cube006_2.geometry}
          material={materials["Material.014"]}
        />
        <mesh
          name="Cube006_3"
          castShadow
          receiveShadow
          geometry={nodes.Cube006_3.geometry}
          material={materials["Material.015"]}
        />
      </group>
      <group
        name="Cube007"
        position={[-22.27510834, 4.07888651, -0.55642003]}
        rotation={[-2.7270711, -0.31701167, 0.13631538]}
        scale={[0.04550787, 0.00555941, 0.200804]}
        userData={{ name: "Cube.007" }}
      >
        <mesh
          name="Cube007_1"
          castShadow
          receiveShadow
          geometry={nodes.Cube007_1.geometry}
          material={materials["Material.015"]}
        />
        <mesh
          name="Cube007_2"
          castShadow
          receiveShadow
          geometry={nodes.Cube007_2.geometry}
          material={materials["Material.016"]}
        />
      </group>
      <mesh
        name="Plane007"
        castShadow
        receiveShadow
        geometry={nodes.Plane007.geometry}
        material={materials["Material.033"]}
        position={[-15.78305531, 1.97084594, -1.30666995]}
        userData={{ name: "Plane.007" }}
      />
      <mesh
        name="Circle002"
        castShadow
        receiveShadow
        geometry={nodes.Circle002.geometry}
        material={materials["Material.025"]}
        position={[-15.63593197, 1.97084594, -1.30666995]}
        userData={{ name: "Circle.002" }}
      />
      <group
        name="Cube008"
        position={[-23.26921082, 1.24883139, -1.24790215]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.03682804, -0.23914909, -0.13975199]}
        userData={{ name: "Cube.008" }}
      >
        <mesh
          name="Cube008_1"
          castShadow
          receiveShadow
          geometry={nodes.Cube008_1.geometry}
          material={materials["Material.031"]}
        />
        <mesh
          name="Cube008_2"
          castShadow
          receiveShadow
          geometry={nodes.Cube008_2.geometry}
          material={materials["Material.032"]}
        />
      </group>
      <mesh
        name="Cube009"
        castShadow
        receiveShadow
        geometry={nodes.Cube009.geometry}
        material={materials["Material.026"]}
        position={[-20.32978058, 1.07692862, 2.74294734]}
        scale={[1.09853351, 1, 0.51731098]}
        userData={{ name: "Cube.009" }}
      />
      <mesh
        name="Cube010"
        castShadow
        receiveShadow
        geometry={nodes.Cube010.geometry}
        material={nodes.Cube010.material}
        position={[-23.30402756, 1.23584831, 2.75070262]}
        scale={[0.01396463, 0.20224226, 0.11958333]}
        userData={{ name: "Cube.010" }}
      />
      <mesh
        name="Circle003"
        castShadow
        receiveShadow
        geometry={nodes.Circle003.geometry}
        material={materials["Material.029"]}
        position={[-23.28310394, 1.23584819, 2.75070238]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.05469041}
        userData={{ name: "Circle.003" }}
      />
      <mesh
        name="Circle005"
        castShadow
        receiveShadow
        geometry={nodes.Circle005.geometry}
        material={materials["Material.030"]}
        position={[-22.34443474, 4.70461321, 0.50457531]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={-0.01636991}
        userData={{ name: "Circle.005" }}
      />
      <mesh
        name="Circle006"
        castShadow
        receiveShadow
        geometry={nodes.Circle006.geometry}
        material={materials["Material.004"]}
        position={[-23.34434509, 5.59141254, 10.86443996]}
        scale={0.39943105}
        userData={{ name: "Circle.006" }}
      />
      <mesh
        name="Circle007"
        castShadow
        receiveShadow
        geometry={nodes.Circle007.geometry}
        material={materials["Material.011"]}
        position={[-23.34434319, 5.71035719, 10.86443901]}
        scale={0.01251971}
        userData={{ name: "Circle.007" }}
      />
      <mesh
        name="Plane008"
        castShadow
        receiveShadow
        geometry={nodes.Plane008.geometry}
        material={materials["Material.012"]}
        position={[-23.64678383, 7.70562124, 10.68409348]}
        rotation={[2.22003961, -0.19273808, -2.07480581]}
        scale={[0.06897982, 0.09527118, 0.03960593]}
        userData={{ name: "Plane.008" }}
      />
      <mesh
        name="Plane009"
        castShadow
        receiveShadow
        geometry={nodes.Plane009.geometry}
        material={materials["Material.019"]}
        position={[-22.7846508, 9.67506504, -0.61346251]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.12125336, 2.68036151, 2.28154635]}
        userData={{ name: "Plane.009" }}
      />
      <mesh
        name="Plane011"
        castShadow
        receiveShadow
        geometry={nodes.Plane011.geometry}
        material={materials["Material.018"]}
        position={[-24.92105675, 8.29513645, -2.3095088]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.12125336, 2.68036151, 2.28154635]}
        userData={{ name: "Plane.011" }}
      />
      <mesh
        name="Cube011"
        castShadow
        receiveShadow
        geometry={nodes.Cube011.geometry}
        material={materials["Material.017"]}
        position={[-23.62016487, 5.81367683, -9.53694725]}
        rotation={[0, -1.51943586, -Math.PI]}
        scale={[-0.06207346, -0.41852722, -0.16451354]}
        userData={{ name: "Cube.011" }}
      />
      <mesh
        name="NurbsPath002"
        castShadow
        receiveShadow
        geometry={nodes.NurbsPath002.geometry}
        material={materials["Material.021"]}
        position={[-23.54632568, 10.50350475, -0.74000645]}
        userData={{ name: "NurbsPath.002" }}
      />
      <mesh
        name="NurbsPath003"
        castShadow
        receiveShadow
        geometry={nodes.NurbsPath003.geometry}
        material={materials["Material.021"]}
        position={[-23.47928429, 10.51754093, -1.00900042]}
        userData={{ name: "NurbsPath.003" }}
      />
      <mesh
        name="NurbsPath004"
        castShadow
        receiveShadow
        geometry={nodes.NurbsPath004.geometry}
        material={materials["Material.021"]}
        position={[-23.59837723, 10.37828064, -0.9502635]}
        rotation={[-0.06660922, 0.2866781, 0.11340729]}
        userData={{ name: "NurbsPath.004" }}
      />
      <mesh
        name="NurbsPath005"
        castShadow
        receiveShadow
        geometry={nodes.NurbsPath005.geometry}
        material={materials["Material.021"]}
        position={[-23.41822243, 10.50938797, -1.00995255]}
        rotation={[0, -0.55834459, 0]}
        userData={{ name: "NurbsPath.005" }}
      />
      <mesh
        name="Plane013"
        castShadow
        receiveShadow
        geometry={nodes.Plane013.geometry}
        material={materials["Material.023"]}
        position={[-21.60066223, 8.50634861, -0.2644197]}
        rotation={[2.47243392, -0.08373013, -2.05806976]}
        scale={[0.06897982, 0.09527118, 0.03960593]}
        userData={{ name: "Plane.013" }}
      />
      <mesh
        name="Plane014"
        castShadow
        receiveShadow
        geometry={nodes.Plane014.geometry}
        material={materials["Material.023"]}
        position={[-21.68002892, 8.49391365, -0.13028792]}
        rotation={[-0.50874775, -0.3860206, -0.87001002]}
        scale={[0.06897982, 0.09527118, 0.03960593]}
        userData={{ name: "Plane.014" }}
      />
      <mesh
        name="Plane015"
        castShadow
        receiveShadow
        geometry={nodes.Plane015.geometry}
        material={materials["Material.023"]}
        position={[-21.65185738, 8.87063694, -0.17852297]}
        rotation={[-0.50874775, -0.3860206, -0.87001002]}
        scale={[0.06897982, 0.09527118, 0.03960593]}
        userData={{ name: "Plane.015" }}
      />
      <mesh
        name="Plane016"
        castShadow
        receiveShadow
        geometry={nodes.Plane016.geometry}
        material={materials["Material.023"]}
        position={[-21.74215698, 8.89922523, -1.09310579]}
        rotation={[-1.99399728, -0.75556112, -1.80454757]}
        scale={[0.06897982, 0.09527118, 0.03960593]}
        userData={{ name: "Plane.016" }}
      />
      <mesh
        name="Plane017"
        castShadow
        receiveShadow
        geometry={nodes.Plane017.geometry}
        material={materials["Material.023"]}
        position={[-21.36631775, 7.71209192, -1.56255484]}
        rotation={[-0.4790584, -0.3624468, -0.8591552]}
        scale={[0.06897982, 0.09527118, 0.03960593]}
        userData={{ name: "Plane.017" }}
      />
      <mesh
        name="Plane018"
        castShadow
        receiveShadow
        geometry={nodes.Plane018.geometry}
        material={materials["Material.023"]}
        position={[-21.47562981, 8.01048279, -1.27600336]}
        rotation={[-0.62765685, -0.47286024, -0.91961416]}
        scale={[0.06897982, 0.09527118, 0.03960593]}
        userData={{ name: "Plane.018" }}
      />
      <mesh
        name="Plane019"
        castShadow
        receiveShadow
        geometry={nodes.Plane019.geometry}
        material={materials["Material.023"]}
        position={[-21.5614357, 8.23286533, -1.14822316]}
        rotation={[-0.96872329, -0.65519103, -1.10397785]}
        scale={[0.06897982, 0.09527118, 0.03960593]}
        userData={{ name: "Plane.019" }}
      />
      <mesh
        name="Plane020"
        castShadow
        receiveShadow
        geometry={nodes.Plane020.geometry}
        material={materials["Material.023"]}
        position={[-21.24995613, 7.54461336, -1.654194]}
        rotation={[-1.7715574, -0.78087464, -1.64964177]}
        scale={[0.06897982, 0.09527118, 0.03960593]}
        userData={{ name: "Plane.020" }}
      />
      <mesh
        name="Plane021"
        castShadow
        receiveShadow
        geometry={nodes.Plane021.geometry}
        material={materials["Material.023"]}
        position={[-21.74608994, 8.5708046, -1.27082515]}
        rotation={[2.38630925, 0.55236278, -2.15926914]}
        scale={[0.06897982, 0.09527119, 0.03960593]}
        userData={{ name: "Plane.021" }}
      />
      <mesh
        name="Plane022"
        castShadow
        receiveShadow
        geometry={nodes.Plane022.geometry}
        material={materials["Material.023"]}
        position={[-22.23208237, 8.8274231, -1.4214524]}
        rotation={[0.19640822, 0.27370414, -0.82635784]}
        scale={[0.06897982, 0.09527118, 0.03960593]}
        userData={{ name: "Plane.022" }}
      />
      <mesh
        name="Plane023"
        castShadow
        receiveShadow
        geometry={nodes.Plane023.geometry}
        material={materials["Material.023"]}
        position={[-22.18243217, 9.07430935, -1.26409662]}
        rotation={[-0.50874775, -0.3860206, -0.87001002]}
        scale={[0.06897982, 0.09527118, 0.03960593]}
        userData={{ name: "Plane.023" }}
      />
      <mesh
        name="Plane024"
        castShadow
        receiveShadow
        geometry={nodes.Plane024.geometry}
        material={materials["Material.023"]}
        position={[-22.2767601, 9.24292088, -1.18345714]}
        rotation={[-0.50874775, -0.3860206, -0.87001002]}
        scale={[0.06897982, 0.09527118, 0.03960593]}
        userData={{ name: "Plane.024" }}
      />
      <mesh
        name="Plane025"
        castShadow
        receiveShadow
        geometry={nodes.Plane025.geometry}
        material={materials["Material.023"]}
        position={[-21.86686516, 9.30332565, -1.15627861]}
        rotation={[-0.50874775, -0.3860206, -0.87001002]}
        scale={[0.06897982, 0.09527118, 0.03960593]}
        userData={{ name: "Plane.025" }}
      />
      <mesh
        name="Plane026"
        castShadow
        receiveShadow
        geometry={nodes.Plane026.geometry}
        material={materials["Material.023"]}
        position={[-21.85239792, 9.44645882, -1.09789503]}
        rotation={[-0.72805824, -0.53658177, -0.96822081]}
        scale={[0.06897983, 0.09527118, 0.03960593]}
        userData={{ name: "Plane.026" }}
      />
      <mesh
        name="Plane027"
        castShadow
        receiveShadow
        geometry={nodes.Plane027.geometry}
        material={materials["Material.023"]}
        position={[-21.84338951, 9.60321617, -1.05945671]}
        rotation={[-0.50874775, -0.3860206, -0.87001002]}
        scale={[0.06897982, 0.09527118, 0.03960593]}
        userData={{ name: "Plane.027" }}
      />
      <mesh
        name="Plane028"
        castShadow
        receiveShadow
        geometry={nodes.Plane028.geometry}
        material={materials["Material.023"]}
        position={[-22.02643585, 8.25919819, 0.38630867]}
        rotation={[0.74556796, 0.63638055, -1.07677861]}
        scale={[0.06897982, 0.09527118, 0.03960593]}
        userData={{ name: "Plane.028" }}
      />
      <mesh
        name="Plane029"
        castShadow
        receiveShadow
        geometry={nodes.Plane029.geometry}
        material={materials["Material.023"]}
        position={[-21.86045837, 7.8562789, 0.55863607]}
        rotation={[-0.50874775, -0.3860206, -0.87001002]}
        scale={[0.06897982, 0.09527118, 0.03960593]}
        userData={{ name: "Plane.029" }}
      />
      <mesh
        name="Plane030"
        castShadow
        receiveShadow
        geometry={nodes.Plane030.geometry}
        material={materials["Material.023"]}
        position={[-22.02254295, 8.70800304, 0.49123916]}
        rotation={[-0.50874775, -0.3860206, -0.87001002]}
        scale={[0.06897982, 0.09527118, 0.03960593]}
        userData={{ name: "Plane.030" }}
      />
      <mesh
        name="Plane031"
        castShadow
        receiveShadow
        geometry={nodes.Plane031.geometry}
        material={materials["Material.023"]}
        position={[-22.03837967, 8.96522713, 0.46878868]}
        rotation={[-0.50874775, -0.3860206, -0.87001002]}
        scale={[0.06897982, 0.09527118, 0.03960593]}
        userData={{ name: "Plane.031" }}
      />
      <mesh
        name="Plane032"
        castShadow
        receiveShadow
        geometry={nodes.Plane032.geometry}
        material={materials["Material.023"]}
        position={[-22.54242325, 9.55016708, 0.27450642]}
        rotation={[-0.50874775, -0.3860206, -0.87001002]}
        scale={[0.06897982, 0.09527118, 0.03960593]}
        userData={{ name: "Plane.032" }}
      />
      <mesh
        name="Plane033"
        castShadow
        receiveShadow
        geometry={nodes.Plane033.geometry}
        material={materials["Material.023"]}
        position={[-21.93357468, 9.69022942, -0.39514932]}
        rotation={[-0.50874775, -0.3860206, -0.87001002]}
        scale={[0.06897982, 0.09527118, 0.03960593]}
        userData={{ name: "Plane.033" }}
      />
      <mesh
        name="Plane034"
        castShadow
        receiveShadow
        geometry={nodes.Plane034.geometry}
        material={materials["Material.023"]}
        position={[-22.575634, 9.87888527, 0.12574932]}
        rotation={[-0.50874775, -0.3860206, -0.87001002]}
        scale={[0.06897982, 0.09527118, 0.03960593]}
        userData={{ name: "Plane.034" }}
      />
      <mesh
        name="Plane035"
        castShadow
        receiveShadow
        geometry={nodes.Plane035.geometry}
        material={materials["Material.023"]}
        position={[-21.71475029, 8.12887096, -0.30567589]}
        rotation={[2.76364294, 0.27686956, -2.31426323]}
        scale={[0.06897982, 0.09527119, 0.03960593]}
        userData={{ name: "Plane.035" }}
      />
      <mesh
        name="Plane036"
        castShadow
        receiveShadow
        geometry={nodes.Plane036.geometry}
        material={materials["Material.023"]}
        position={[-21.44787407, 7.79800177, -0.4048498]}
        rotation={[0.80559289, 0.66104043, -1.11305303]}
        scale={[0.06897982, 0.09527118, 0.03960593]}
        userData={{ name: "Plane.036" }}
      />
      <mesh
        name="Plane037"
        castShadow
        receiveShadow
        geometry={nodes.Plane037.geometry}
        material={materials["Material.023"]}
        position={[-21.6539135, 9.05637741, -0.21302879]}
        rotation={[-0.50874775, -0.3860206, -0.87001002]}
        scale={[0.06897982, 0.09527118, 0.03960593]}
        userData={{ name: "Plane.037" }}
      />
      <mesh
        name="Plane038"
        castShadow
        receiveShadow
        geometry={nodes.Plane038.geometry}
        material={materials["Material.023"]}
        position={[-21.65990067, 9.24208832, -0.26867378]}
        rotation={[-0.50874775, -0.3860206, -0.87001002]}
        scale={[0.06897982, 0.09527118, 0.03960593]}
        userData={{ name: "Plane.038" }}
      />
      <mesh
        name="Plane039"
        castShadow
        receiveShadow
        geometry={nodes.Plane039.geometry}
        material={materials["Material.023"]}
        position={[-21.69093704, 9.37381554, -0.3064667]}
        rotation={[-0.50874775, -0.3860206, -0.87001002]}
        scale={[0.06897982, 0.09527118, 0.03960593]}
        userData={{ name: "Plane.039" }}
      />
      <mesh
        name="Plane040"
        castShadow
        receiveShadow
        geometry={nodes.Plane040.geometry}
        material={materials["Material.023"]}
        position={[-21.73805809, 9.48286629, -0.32313254]}
        rotation={[-0.50874775, -0.3860206, -0.87001002]}
        scale={[0.06897982, 0.09527118, 0.03960593]}
        userData={{ name: "Plane.040" }}
      />
      <mesh
        name="Plane041"
        castShadow
        receiveShadow
        geometry={nodes.Plane041.geometry}
        material={materials["Material.023"]}
        position={[-21.88364983, 9.69469738, -1.01208711]}
        rotation={[-0.50874775, -0.3860206, -0.87001002]}
        scale={[0.06897982, 0.09527118, 0.03960593]}
        userData={{ name: "Plane.041" }}
      />
      <mesh
        name="Plane042"
        castShadow
        receiveShadow
        geometry={nodes.Plane042.geometry}
        material={materials["Material.023"]}
        position={[-21.88329124, 9.76733017, -0.7874645]}
        rotation={[-0.50874775, -0.3860206, -0.87001002]}
        scale={[0.06897982, 0.09527118, 0.03960593]}
        userData={{ name: "Plane.042" }}
      />
      <mesh
        name="Plane043"
        castShadow
        receiveShadow
        geometry={nodes.Plane043.geometry}
        material={materials["Material.023"]}
        position={[-22.00684738, 9.89147282, -0.72482622]}
        rotation={[-0.50874775, -0.3860206, -0.87001002]}
        scale={[0.06897982, 0.09527118, 0.03960593]}
        userData={{ name: "Plane.043" }}
      />
      <mesh
        name="Plane044"
        castShadow
        receiveShadow
        geometry={nodes.Plane044.geometry}
        material={materials["Material.023"]}
        position={[-22.61375809, 9.5173254, -1.2413063]}
        rotation={[-0.50874775, -0.3860206, -0.87001002]}
        scale={[0.06897982, 0.09527118, 0.03960593]}
        userData={{ name: "Plane.044" }}
      />
      <mesh
        name="Plane045"
        castShadow
        receiveShadow
        geometry={nodes.Plane045.geometry}
        material={materials["Material.023"]}
        position={[-22.38250351, 9.46611786, -1.24365962]}
        rotation={[-0.50874775, -0.3860206, -0.87001002]}
        scale={[0.06897982, 0.09527118, 0.03960593]}
        userData={{ name: "Plane.045" }}
      />
      <mesh
        name="Plane046"
        castShadow
        receiveShadow
        geometry={nodes.Plane046.geometry}
        material={materials["Material.023"]}
        position={[-22.64391327, 9.64904213, -1.2094326]}
        rotation={[-0.50874775, -0.3860206, -0.87001002]}
        scale={[0.06897982, 0.09527118, 0.03960593]}
        userData={{ name: "Plane.046" }}
      />
      <mesh
        name="Plane047"
        castShadow
        receiveShadow
        geometry={nodes.Plane047.geometry}
        material={materials["Material.023"]}
        position={[-22.64957619, 9.77511883, -1.16621017]}
        rotation={[-0.50874775, -0.3860206, -0.87001002]}
        scale={[0.06897982, 0.09527118, 0.03960593]}
        userData={{ name: "Plane.047" }}
      />
      <mesh
        name="Plane048"
        castShadow
        receiveShadow
        geometry={nodes.Plane048.geometry}
        material={materials["Material.023"]}
        position={[-22.0081501, 9.83160019, -0.32996753]}
        rotation={[-0.50874775, -0.3860206, -0.87001002]}
        scale={[0.06897982, 0.09527118, 0.03960593]}
        userData={{ name: "Plane.048" }}
      />
      <mesh
        name="Plane049"
        castShadow
        receiveShadow
        geometry={nodes.Plane049.geometry}
        material={materials["Material.023"]}
        position={[-22.71136093, 10.11717319, -0.29329506]}
        rotation={[0.20525359, -0.33104713, -1.48904837]}
        scale={[0.07555169, 0.10434788, 0.04337928]}
        userData={{ name: "Plane.049" }}
      />
      <mesh
        name="Plane050"
        castShadow
        receiveShadow
        geometry={nodes.Plane050.geometry}
        material={materials["Material.023"]}
        position={[-22.72496414, 10.11205864, -0.49028957]}
        rotation={[0.20525359, -0.33104713, -1.48904837]}
        scale={[0.07555169, 0.10434788, 0.04337928]}
        userData={{ name: "Plane.050" }}
      />
      <mesh
        name="Plane051"
        castShadow
        receiveShadow
        geometry={nodes.Plane051.geometry}
        material={materials["Material.023"]}
        position={[-22.7654705, 10.13507271, -0.8151449]}
        rotation={[0.20525359, -0.33104713, -1.48904837]}
        scale={[0.07555169, 0.10434788, 0.04337928]}
        userData={{ name: "Plane.051" }}
      />
      <mesh
        name="Plane052"
        castShadow
        receiveShadow
        geometry={nodes.Plane052.geometry}
        material={materials["Material.023"]}
        position={[-22.53244972, 10.12077236, -0.67471707]}
        rotation={[0.20525359, -0.33104713, -1.48904837]}
        scale={[0.07555169, 0.10434788, 0.04337928]}
        userData={{ name: "Plane.052" }}
      />
      <mesh
        name="Plane053"
        castShadow
        receiveShadow
        geometry={nodes.Plane053.geometry}
        material={materials["Material.023"]}
        position={[-22.71779823, 10.07071686, -0.82826859]}
        rotation={[0.20525359, -0.33104713, -1.48904837]}
        scale={[0.07555169, 0.10434788, 0.04337928]}
        userData={{ name: "Plane.053" }}
      />
      <mesh
        name="Plane054"
        castShadow
        receiveShadow
        geometry={nodes.Plane054.geometry}
        material={materials["Material.023"]}
        position={[-22.60696983, 10.07071686, -0.7568444]}
        rotation={[0.20525359, -0.33104713, -1.48904837]}
        scale={[0.07555169, 0.10434788, 0.04337928]}
        userData={{ name: "Plane.054" }}
      />
      <mesh
        name="Plane055"
        castShadow
        receiveShadow
        geometry={nodes.Plane055.geometry}
        material={materials["Material.023"]}
        position={[-22.69529915, 10.20657921, -0.72120279]}
        rotation={[0.20525359, -0.33104713, -1.48904837]}
        scale={[0.07555169, 0.10434788, 0.04337928]}
        userData={{ name: "Plane.055" }}
      />
      <mesh
        name="Plane056"
        castShadow
        receiveShadow
        geometry={nodes.Plane056.geometry}
        material={materials["Material.023"]}
        position={[-22.66744995, 10.05980206, -0.76436466]}
        rotation={[0.20525359, -0.33104713, -1.48904837]}
        scale={[0.07555169, 0.10434788, 0.04337928]}
        userData={{ name: "Plane.056" }}
      />
      <mesh
        name="Plane057"
        castShadow
        receiveShadow
        geometry={nodes.Plane057.geometry}
        material={materials["Material.023"]}
        position={[-22.78601074, 10.02409935, -0.78892207]}
        rotation={[0.20525359, -0.33104713, -1.48904837]}
        scale={[0.07555169, 0.10434788, 0.04337928]}
        userData={{ name: "Plane.057" }}
      />
      <mesh
        name="Plane058"
        castShadow
        receiveShadow
        geometry={nodes.Plane058.geometry}
        material={materials["Material.023"]}
        position={[-22.51321983, 10.07963753, -0.74080998]}
        rotation={[0.20525359, -0.33104713, -1.48904837]}
        scale={[0.07555169, 0.10434788, 0.04337928]}
        userData={{ name: "Plane.058" }}
      />
      <mesh
        name="Plane059"
        castShadow
        receiveShadow
        geometry={nodes.Plane059.geometry}
        material={materials["Material.023"]}
        position={[-22.43619347, 10.18079567, -0.70027041]}
        rotation={[0.20525359, -0.33104713, -1.48904837]}
        scale={[0.07555169, 0.10434788, 0.04337928]}
        userData={{ name: "Plane.059" }}
      />
      <mesh
        name="Plane060"
        castShadow
        receiveShadow
        geometry={nodes.Plane060.geometry}
        material={materials["Material.023"]}
        position={[-22.44280624, 10.17588806, -0.43929812]}
        rotation={[0.20525359, -0.33104713, -1.48904837]}
        scale={[0.07555169, 0.10434788, 0.04337928]}
        userData={{ name: "Plane.060" }}
      />
      <mesh
        name="Plane061"
        castShadow
        receiveShadow
        geometry={nodes.Plane061.geometry}
        material={materials["Material.023"]}
        position={[-22.86600494, 9.97707272, -0.76037657]}
        rotation={[0.20525359, -0.33104713, -1.48904837]}
        scale={[0.07555169, 0.10434788, 0.04337928]}
        userData={{ name: "Plane.061" }}
      />
      <mesh
        name="Plane062"
        castShadow
        receiveShadow
        geometry={nodes.Plane062.geometry}
        material={materials["Material.023"]}
        position={[-22.85315323, 10.18360996, -0.62042171]}
        rotation={[0.20525359, -0.33104713, -1.48904837]}
        scale={[0.07555169, 0.10434788, 0.04337928]}
        userData={{ name: "Plane.062" }}
      />
      <mesh
        name="Plane063"
        castShadow
        receiveShadow
        geometry={nodes.Plane063.geometry}
        material={materials["Material.023"]}
        position={[-22.78403091, 10.10916615, -1.02833736]}
        rotation={[0.20525359, -0.33104713, -1.48904837]}
        scale={[0.07555169, 0.10434788, 0.04337928]}
        userData={{ name: "Plane.063" }}
      />
      <mesh
        name="Plane064"
        castShadow
        receiveShadow
        geometry={nodes.Plane064.geometry}
        material={materials["Material.023"]}
        position={[-22.7500267, 10.06861782, -0.88563102]}
        rotation={[0.20525359, -0.33104713, -1.48904837]}
        scale={[0.07555169, 0.10434788, 0.04337928]}
        userData={{ name: "Plane.064" }}
      />
      <mesh
        name="Plane065"
        castShadow
        receiveShadow
        geometry={nodes.Plane065.geometry}
        material={materials["Material.023"]}
        position={[-22.75374031, 10.03241539, -1.06199396]}
        rotation={[0.20525359, -0.33104713, -1.48904837]}
        scale={[0.07555169, 0.10434788, 0.04337928]}
        userData={{ name: "Plane.065" }}
      />
      <mesh
        name="Plane066"
        castShadow
        receiveShadow
        geometry={nodes.Plane066.geometry}
        material={materials["Material.023"]}
        position={[-22.71448135, 9.98028183, -0.9182846]}
        rotation={[0.20525359, -0.33104713, -1.48904837]}
        scale={[0.07555169, 0.10434788, 0.04337928]}
        userData={{ name: "Plane.066" }}
      />
      <mesh
        name="Plane067"
        castShadow
        receiveShadow
        geometry={nodes.Plane067.geometry}
        material={materials["Material.023"]}
        position={[-22.81907845, 10.20763683, -0.95114625]}
        rotation={[0.20525359, -0.33104713, -1.48904837]}
        scale={[0.07555169, 0.10434788, 0.04337928]}
        userData={{ name: "Plane.067" }}
      />
      <mesh
        name="Plane068"
        castShadow
        receiveShadow
        geometry={nodes.Plane068.geometry}
        material={materials["Material.023"]}
        position={[-22.67178917, 9.96579742, -0.59499443]}
        rotation={[0.20525359, -0.33104713, -1.48904837]}
        scale={[0.07555169, 0.10434788, 0.04337928]}
        userData={{ name: "Plane.068" }}
      />
      <mesh
        name="Plane069"
        castShadow
        receiveShadow
        geometry={nodes.Plane069.geometry}
        material={materials["Material.023"]}
        position={[-22.69145775, 10.04689121, -0.44945395]}
        rotation={[0.20525359, -0.33104713, -1.48904837]}
        scale={[0.07555169, 0.10434788, 0.04337928]}
        userData={{ name: "Plane.069" }}
      />
      <mesh
        name="Plane070"
        castShadow
        receiveShadow
        geometry={nodes.Plane070.geometry}
        material={materials["Material.023"]}
        position={[-22.7631588, 10.17867088, -0.56722826]}
        rotation={[0.20525359, -0.33104713, -1.48904837]}
        scale={[0.07555169, 0.10434788, 0.04337928]}
        userData={{ name: "Plane.070" }}
      />
      <mesh
        name="Plane071"
        castShadow
        receiveShadow
        geometry={nodes.Plane071.geometry}
        material={materials["Material.023"]}
        position={[-22.70960617, 10.14101791, -0.23878649]}
        rotation={[0.20525359, -0.33104713, -1.48904837]}
        scale={[0.07555169, 0.10434788, 0.04337928]}
        userData={{ name: "Plane.071" }}
      />
      <mesh
        name="Plane072"
        castShadow
        receiveShadow
        geometry={nodes.Plane072.geometry}
        material={materials["Material.023"]}
        position={[-22.70072937, 10.19986916, -0.05706311]}
        rotation={[0.20525356, -0.33104709, -1.48904836]}
        scale={[0.06897982, 0.09527118, 0.03960593]}
        userData={{ name: "Plane.072" }}
      />
      <mesh
        name="Plane073"
        castShadow
        receiveShadow
        geometry={nodes.Plane073.geometry}
        material={materials["Material.023"]}
        position={[-22.18374252, 10.12897491, -0.36637354]}
        rotation={[0.20525359, -0.33104713, -1.48904837]}
        scale={[0.07555169, 0.10434788, 0.04337928]}
        userData={{ name: "Plane.073" }}
      />
      <mesh
        name="Plane074"
        castShadow
        receiveShadow
        geometry={nodes.Plane074.geometry}
        material={materials["Material.023"]}
        position={[-22.17282486, 10.17045116, -0.73998272]}
        rotation={[0.20525359, -0.33104713, -1.48904837]}
        scale={[0.07555169, 0.10434788, 0.04337928]}
        userData={{ name: "Plane.074" }}
      />
      <mesh
        name="Plane075"
        castShadow
        receiveShadow
        geometry={nodes.Plane075.geometry}
        material={materials["Material.023"]}
        position={[-22.78894234, 10.10654449, -1.16671026]}
        rotation={[0.20525356, -0.33104709, -1.48904836]}
        scale={[0.06897982, 0.09527118, 0.03960593]}
        userData={{ name: "Plane.075" }}
      />
      <mesh
        name="Plane076"
        castShadow
        receiveShadow
        geometry={nodes.Plane076.geometry}
        material={materials["Material.012"]}
        position={[-23.54421234, 7.71554947, 11.07083797]}
        rotation={[-2.87585926, -0.53609257, -1.59596012]}
        scale={[0.06897982, 0.09527118, 0.03960593]}
        userData={{ name: "Plane.076" }}
      />
      <mesh
        name="Cube012"
        castShadow
        receiveShadow
        geometry={nodes.Cube012.geometry}
        material={materials["Wood N/ Texture"]}
        position={[-8.59805489, 6.62916613, 23.04887962]}
        scale={[3.4927547, 1.07915759, 0.85451847]}
        userData={{ name: "Cube.012" }}
      />
      <group
        name="Plane082"
        position={[-8.09012032, 6.4817915, 22.64120674]}
        rotation={[1.64385302, 1.42622664, 3.06776896]}
        scale={[0.36577845, 1, 0.09831779]}
        userData={{ name: "Plane.082" }}
      >
        <mesh
          name="Plane084"
          castShadow
          receiveShadow
          geometry={nodes.Plane084.geometry}
          material={materials["Material.036"]}
        />
        <mesh
          name="Plane084_1"
          castShadow
          receiveShadow
          geometry={nodes.Plane084_1.geometry}
          material={materials["Material.037"]}
        />
        <mesh
          name="Plane084_2"
          castShadow
          receiveShadow
          geometry={nodes.Plane084_2.geometry}
          material={materials["Material.038"]}
        />
        <mesh
          name="Plane084_3"
          castShadow
          receiveShadow
          geometry={nodes.Plane084_3.geometry}
          material={materials["Material.039"]}
        />
      </group>
      <mesh
        name="Cube"
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials["Material.003"]}
        position={[0.47476494, 0, 0.5534476]}
        rotation={[Math.PI, -1.56455169, Math.PI]}
        scale={[23.32167816, 0.07759643, 23.71529388]}
        userData={{ name: "Cube" }}
      />
      <group
        name="Plane"
        position={[-23.48134613, -0.07398158, 0.12562239]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.17732143, -16.4496212, -23.71066475]}
        userData={{ name: "Plane" }}
      >
        <mesh
          name="Plane_1"
          castShadow
          receiveShadow
          geometry={nodes.Plane_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          name="Plane_2"
          castShadow
          receiveShadow
          geometry={nodes.Plane_2.geometry}
          material={materials["Material.006"]}
        />
      </group>
      <mesh
        name="Plane002"
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={materials["Material.006"]}
        position={[-23.48134613, -0.07398158, 0.12562239]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.17732143, -16.4496212, -23.71066475]}
        userData={{ name: "Plane.002" }}
      />
      <mesh
        name="Plane003"
        castShadow
        receiveShadow
        geometry={nodes.Plane003.geometry}
        material={materials["Material.007"]}
        position={[-40.70485687, -0.07398158, 0.12562239]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.17732143, -10.95129013, -23.71066475]}
        userData={{ name: "Plane.003" }}
      />
      <mesh
        onClick={()=>{window.open("https://koke-1.github.io/Soccer/", '_blank').focus();}}
        onPointerOver={()=>{document.body.style.cursor = "pointer" }}
        onPointerOut={()=>{document.body.style.cursor = "default" }}
        name="Poster"
        castShadow
        receiveShadow
        geometry={nodes.Poster.geometry}
        material={materials["Material.035"]}
        position={[-23.2364502, 10.48787212, 18.80779648]}
        rotation={[1.55986248, 0, -Math.PI / 2]}
        scale={[2.34092879, 1, 3.12861109]}
        userData={{ name: "Poster" }}
      />
    </group>
  );
}

useGLTF.preload("/ROOM.glb");
